### ISSUE TITLE
Bug: vc-labels not loading 

### ISSUE THREAD

**Issue by vzinche** [platybrowser/platybrowser-fiji#26]
File name: /g/arendt/EM_6dpf_segmentation/EM-Prospr/em-segmented-cellular-models-labels.h5
dtype: int16
Error message: attached
![Screenshot from 2019-05-24 11-29-13](https://user-images.githubusercontent.com/32451366/58317990-392b5700-7e17-11e9-96ee-2ef41dd0962a.png)

**Comment by vzinche** [comment]
Btw, when I try to remove the file from the browser (clicking 'X') everything just gets stalled :)

**Comment by tischi** [comment]
@vzinche is this still an issue? if not, could you please close it?

**Comment by vzinche** [comment]
it still can't be loaded. I'll try once again when @constantinpape moves this file to segmentations

**Comment by constantinpape** [comment]
> it still can't be loaded. I'll try once again when @constantinpape moves this file to segmentations

This depends on how we resolve https://github.com/platybrowser/platybrowser-backend/issues/10.

**Comment by constantinpape** [comment]
This should be fixed, could you try again @vzinche?

**Comment by vzinche** [comment]
![Screenshot from 2020-02-11 09-55-40](https://user-images.githubusercontent.com/32451366/74222439-cb7ccf00-4cb4-11ea-9049-2711fa67e037.png)

**Comment by constantinpape** [comment]
@tischer we are still seeing some nullpointer exceptions when the file is loaded.
I checked and the dtype is int16, did you maybe forget to push the fixes for empty int16 chunks we made yesterday?
I will also check the file locally.

Also the virtual-cells still end up in the `prospr` dropdown, not in the `prospr segmentation` dropdown where they should be. (I checked and their type is `Segmentation` in `images.json`).

**Comment by tischi** [comment]
> I checked and the dtype is int16, did you maybe forget to push the fixes for empty int16 chunks we made yesterday?

Does it work now?

### TODO
- [ ] Also the virtual-cells still end up in the prospr dropdown, not in the prospr segmentation dropdown where they should be. (I checked and their type is Segmentation in images.json).

**Comment by constantinpape** [comment]
Works now, virtual cells are displayed properly and they show up in the correct dropdown menu.
