### ISSUE TITLE
Imperceptible colors for segmentation objects

### ISSUE THREAD

**Issue by constantinpape** [platybrowser/platybrowser-fiji#37]
Some of the colors used for the segmentation objects cannot be distinguished from the background.
See for example these two images. The first shows all the cilia in the bundle with color on (but not perceptible in the image), the second shows them with color off.
![Screenshot from 2019-11-07 15-37-44](https://user-images.githubusercontent.com/4263537/68398699-72f9db00-0175-11ea-9752-3bde9eb1e24b.png)
![Screenshot from 2019-11-07 15-37-53](https://user-images.githubusercontent.com/4263537/68398713-77be8f00-0175-11ea-8944-34872d48fc99.png)

**Comment by tischi** [comment]
I can see some colours in the upper image...
You think it is just because they do not nicely differ from the grey?
Maybe I have to see this on your computer.

**Comment by constantinpape** [comment]
> I can see some colours in the upper image...
> You think it is just because they do not nicely differ from the grey?
> Maybe I have to see this on your computer.

I agree, in the screenshot there is some color visible, but it's still very faint.
(Also, there is one object which is colored in green, for which the color can be made out.)
But on screen it does not differ from the gray-scale at all.
Maybe increasing saturation would help?

**Comment by tischi** [comment]
@constantinpape 
We discussed the idea to remove colors that are too close to gray. Shall I still do this?

**Comment by constantinpape** [comment]
> @constantinpape
> We discussed the idea to remove colors that are too close to gray. Shall I still do this?

Yes please do this.

**Comment by tischi** [comment]
should be done. will upload soon.
```
       for (int i = 1; i < r.length; i++)
		{
			if ( ( Math.abs( g[ i ] - r[ i ] ) < MINIMUM_RGB_DIFFERENCE )
					&& ( Math.abs( g[ i ] - b[ i ] ) < MINIMUM_RGB_DIFFERENCE )
					&& ( Math.abs( r[ i ] - b[ i ] ) < MINIMUM_RGB_DIFFERENCE ) )
				continue; // too grayish

			indices.add( ARGBType.rgba(
					r[ i ],
					g[ i ],
					b[ i ],
					alpha ));
		}
```
with `MINIMUM_RGB_DIFFERENCE` = 50 we have now 218 instead of 256 colours.
