### ISSUE TITLE
Don't color label 0 when coloring by category

### ISSUE THREAD

**Issue by constantinpape** [platybrowser/platybrowser-fiji#45]
Currently, values that are zero get assigned a color when doing `Color By Column` -> `Categorical - Glasbey`.
Usually zero means that the label / marker is not present though and I would suggest not to color it.

**Comment by tischi** [comment]
I am not sure, because, e.g., a circularity measure could be 0.
You could put there a string to `NaN`. 
I already parse this and do not color it. 
Would that work for you?

**Comment by constantinpape** [comment]
> You could put there a string `NaN`.

This is not a good solution, because many tables are used for down-stream analysis where 0 has a very different meaning from `NaN`.

> I am not sure, because, e.g., a circularity measure could be 0.

How about offering to Categorical color modes, one that includes 0, one that ignores it?

**Comment by tischi** [comment]
> How about offering to Categorical color modes, one that includes 0, one that ignores it?

That could be an idea. I will look at it.

**Comment by tischi** [comment]
I made code compatible with above idea, but currently it is too much work to implement the UI. Thus I, hardcoded it for now:
```
		this.inputToFixedColor.put( "NaN", NO_COLOR );
		this.inputToFixedColor.put( "None", NO_COLOR );
		this.inputToFixedColor.put( "0", NO_COLOR );
```
I'll leave the issue open until I implement the UI.

**Comment by K-Meech** [comment]
For the clustering columns, there is currently a cluster 0, so this will be affected by this. Could we leave zero out of the hardcoding for now? Otherwise, I can look into changing the cluster_ids to avoid this...

**Comment by constantinpape** [comment]
> For the clustering columns, there is currently a cluster 0, so this will be affected by this. Could we leave zero out of the hardcoding for now? Otherwise, I can look into changing the cluster_ids to avoid this...

There are a few tables though where we don't want 0 to be colored, e.g. the region table.
 @tischer  Coulde we have two glasbey color maps, one including and one excluding glasbey?

**Comment by tischi** [comment]
@K-Meech @constantinpape 
I can make it optional. I realised it is a bit tricky, because in the categorical case I treat the columns as strings, so what is zero? `"0"`, `"0.0"`, ... others?

**Comment by K-Meech** [comment]
Ah - I see. For me just "0" and "0.0" would cover the tables I'm using.

**Comment by tischi** [comment]
Ok. I put both. 
```
		if ( isZeroTransparent )
		{
			coloringModel.putInputToFixedColor( "0", CategoryTableRowColumnColoringModel.TRANSPARENT );
			coloringModel.putInputToFixedColor( "0.0", CategoryTableRowColumnColoringModel.TRANSPARENT );
		}
```

Should work now. 
Will upload soon.
