### ISSUE TITLE
Show gene expression without long prefix

### ISSUE THREAD

**Issue by vzinche** [platybrowser/platybrowser-fiji#46]
The 'search gene in this position' (keyboard shortcut D) outputs results like this:

![Screenshot from 2020-02-05 10-06-14](https://user-images.githubusercontent.com/32451366/73827067-30d94780-47ff-11ea-829e-aacdd96cba7d.png)

Could you please remove the prefix "prospr_6d_blahblah"?

**Comment by tischi** [comment]
done.
